[package]
authors = ["cohama <cohama@live.jp>"]
name = "deeplearning"
version = "0.1.0"

[dependencies]
alga = "0.5.1"
nalgebra = "0.12.3"
rand = "0.3.15"
typenum = "1.9.0"

[dependencies.rsplot]
path = "../rsplot"
